apiVersion: 1

deleteDatasources:
  - name: Influx
    orgId: 1

datasources:
  - name: Influx
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influx:8086
    database: metrics
    isDefault: true
    editable: false
